#
# Copyright (c) 2019 Connexta, LLC
#
# Released under the GNU Lesser General Public License version 3; see
# https://www.gnu.org/licenses/lgpl-3.0.html
#

openapi: 3.0.2
info:
  version: ${project.version}
  title: Ingest API
  description: >
    The Ingest API is defined to provide clients with the ability to ingest a dataset for
    validation, transformation, and storage.
  contact:
    name: Connexta
  license:
    name: GNU Lesser General Public License
    url: 'http://www.gnu.org/licenses/lgpl.html'
servers:
  - url: ${rest.server.url}
paths:
  /ingest:
    post:
      summary: Ingest endpoint for a dataset.
      description: >
        A system can use the Ingest endpoint to ingest a dataset for validation, transformation, and
        storage.
      operationId: ingest
      tags:
        - ingest
      parameters:
        - $ref: '#/components/parameters/Accept-Version'
        - $ref: '#/components/parameters/Last-Modified'
      requestBody:
        required: true
        description: >
          The body of the ingest request that includes the dataset.
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/IngestRequest'
      responses:
        '202':
          $ref: '#/components/responses/Accepted'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '501':
          $ref: '#/components/responses/NotImplemented'
components:
  responses:
    Accepted:
      description: >
        The ingest request was accepted.
      headers:
        'Content-Version':
          $ref: '#/components/headers/ContentVersion'
    BadRequest:
      description: >
        The client message could not understood by the server due to invalid format or syntax.
      headers:
        'Content-Version':
          $ref: '#/components/headers/ContentVersion'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    Unauthorized:
      description: >
        The client could not be authenticated.
      headers:
        'Content-Version':
          $ref: '#/components/headers/ContentVersion'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    Forbidden:
      description: >
        The client does not have permission.
      headers:
        'Content-Version':
          $ref: '#/components/headers/ContentVersion'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    NotImplemented:
      description: >
        The requested API version is not supported and therefore not implemented.
      headers:
        'Content-Version':
          $ref: '#/components/headers/ContentVersion'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
  parameters:
    Accept-Version:
      name: Accept-Version
      in: header
      description: >
        The minimal API version from which the client using this API will accept responses.
      required: true
      schema:
        $ref: '#/components/schemas/Version'
    Last-Modified:
      name: Last-Modified
      in: header
      description: >
        The last modified time of the dataset to be ingested.
      required: true
      schema:
        type: string
        format: date-time
        example: '2017-06-11T14:32:28Z'
  headers:
    ContentVersion:
      description: >
        The API version used by the server to produce the REST message. The server will accept
        messages for any minor versions prior to this one.
      required: true
      schema:
        $ref: '#/components/schemas/Version'
      examples:
        major.minor:
          value: '1.2'
          summary: A released minor version
        major.minor.patch:
          value: '1.0.3'
          summary: A patched version
        dev:
          value: '1.2.0-SNAPSHOT'
          summary: A development version
  schemas:
    IngestRequest:
      type: object
      properties:
        file:
          $ref: '#/components/schemas/File'
        correlationId:
          $ref: '#/components/schemas/CorrelationId'
        metacard:
          $ref: '#/components/schemas/Metacard'
      required:
        - file
        - correlationId
        - metacard
    File:
      description: >
        A file attachment that is sent in the ingest request. The current maximum is the character
        equivalent of 10GB.
      type: string
      format: binary
      minLength: 1
      maxLength: 14316557655
    CorrelationId:
      description: >
        A unique correlation id for the dataset to be ingested which will allow the client to
        perform actions with the dataset and/or any other information associated with it in the
        future. Only one dataset can exist with a given correlation id. This means that a request to
        ingest a dataset with an existing correlation id will result in a failure with no changes to
        the existing dataset or associated information.
      type: string
      minLength: 1
      maxLength: 256
    Metacard:
      description: >
        A metacard.xml attachment that is sent in the ingest request to enhance validation and
        transformation. The current maximum is the character equivalent of 10GB.
      type: string
      format: binary
      minLength: 1
      maxLength: 14316557655
    Version:
      description: Version number.
      type: string
      minLength: 3
      maxLength: 80
      pattern: '^([1-9]([0-9]+)?)\.(0|([1-9]([0-9]+)?))(\.(0|([1-9]([0-9]+)?))(-.*)?)?$'
      example: 1.2, 2.4.3, 0.2.5-SNAPSHOT
    ErrorMessage:
      description: Error message information.
      type: object
      required:
        - timestamp
        - path
        - status
        - error
        - message
      properties:
        timestamp:
          type: string
          format: date-time
          description: The server time when the error was generated.
          example: '2019-05-09T14:47:13.101+00:00'
        path:
          type: string
          description: The path for the REST request that generated this error.
          example: /ingest
        status:
          type: integer
          format: int32
          description: The corresponding HTTP status code.
          example: 200
        code:
          type: integer
          format: int32
          description: >
            An optional more specific code corresponding to the error (specific codes need to be
            documented).
        error:
          type: string
          description: The corresponding HTTP reason phrase.
          minLength: 1
          example: Bad Request
        message:
          type: string
          description: Specific information about the error.
          minLength: 1
          example: Validation failed for object='systemInfo'.
        details:
          type: array
          items:
            type: string
          description: Optional detailed information about the error.
